import type { IBrand } from "@/pages/brands/type/brandMaster";

export const MOCK_BRANDS: IBrand[] = [
  {
    code: "APL",
    name: "Apple",
    country: "United States",
    website: "https://www.apple.com",
    supportEmail: "support@apple.com",
    isActive: true,
    description: "Premium consumer electronics and software brand.",
  },
  {
    code: "SMSNG",
    name: "Samsung",
    country: "South Korea",
    website: "https://www.samsung.com",
    supportEmail: "care@samsung.com",
    isActive: true,
    description: "Global brand for mobiles, TVs, and appliances.",
  },
  {
    code: "NVDA",
    name: "NVIDIA",
    country: "United States",
    website: "https://www.nvidia.com",
    supportEmail: "support@nvidia.com",
    isActive: true,
    description: "Graphics cards and AI hardware/software.",
  },
  {
    code: "BOAT",
    name: "boAt",
    country: "India",
    website: "https://www.boat-lifestyle.com",
    supportEmail: "support@boat-lifestyle.com",
    isActive: true,
    description: "Indian brand for audio and lifestyle accessories.",
  },
  {
    code: "LG",
    name: "LG",
    country: "South Korea",
    website: "https://www.lg.com",
    supportEmail: "support@lg.com",
    isActive: true,
    description: "Home appliances, TVs, and consumer electronics.",
  },
  {
    code: "PHLP",
    name: "Philips",
    country: "Netherlands",
    website: "https://www.philips.com",
    supportEmail: "support@philips.com",
    isActive: true,
    description: "Lighting, kitchen appliances, and grooming products.",
  },
  {
    code: "NO-BRAND",
    name: "Generic / Unbranded",
    country: "",
    website: "",
    supportEmail: "",
    isActive: true,
    description: "Fallback brand for unbranded or custom products.",
  },
  {
    code: "OLD-MFG",
    name: "Legacy Manufacturer",
    country: "India",
    website: "https://legacy-mfg.example.com",
    supportEmail: "support@legacy-mfg.example.com",
    isActive: false,
    description: "Example inactive brand for testing.",
  },
];
