import type { ICategory } from "@/pages/categories/type/categoryMaster";

export const MOCK_CATEGORIES: ICategory[] = [
  {
    code: "ELEC",
    name: "Electronics",
    level: 1,
    isActive: true,
    description: "Phones, laptops, and electronic accessories",
  },
  {
    code: "ELEC-MOB",
    name: "Mobile Phones",
    parentCode: "ELEC",
    level: 2,
    isActive: true,
    description: "Smartphones and feature phones",
  },
  {
    code: "ELEC-MOB-ACC",
    name: "Mobile Accessories",
    parentCode: "ELEC-MOB",
    level: 3,
    isActive: true,
    description: "Cases, chargers, screen guards, and more",
  },
  {
    code: "ELEC-LAP",
    name: "Laptops & Desktops",
    parentCode: "ELEC",
    level: 2,
    isActive: true,
    description: "Laptops, desktops, and computer accessories",
  },
  {
    code: "FASH",
    name: "Fashion",
    level: 1,
    isActive: true,
    description: "Clothing, footwear, and accessories",
  },
  {
    code: "FASH-MEN",
    name: "Men's Fashion",
    parentCode: "FASH",
    level: 2,
    isActive: true,
    description: "Men's clothing and footwear",
  },
  {
    code: "FASH-WOM",
    name: "Women's Fashion",
    parentCode: "FASH",
    level: 2,
    isActive: true,
    description: "Women's clothing and footwear",
  },
  {
    code: "HOME",
    name: "Home & Kitchen",
    level: 1,
    isActive: true,
    description: "Appliances, decor, and kitchenware",
  },
  {
    code: "HOME-KITCH",
    name: "Kitchen Appliances",
    parentCode: "HOME",
    level: 2,
    isActive: true,
    description: "Mixers, blenders, and other appliances",
  },
  {
    code: "SALE-ARCH",
    name: "Archived / Inactive",
    level: 1,
    isActive: false,
    description: "Example inactive category for testing",
  },
];
