export const MOCK_COUNTRIES = [
  { id: 1, name: "India", code: "in" },
  { id: 2, name: "United States", code: "us" },
  { id: 3, name: "United Kingdom", code: "gb" },
  { id: 4, name: "Canada", code: "ca" },
  { id: 5, name: "Australia", code: "au" },
  { id: 6, name: "Germany", code: "de" },
  { id: 7, name: "France", code: "fr" },
  { id: 8, name: "Italy", code: "it" },
  { id: 9, name: "Spain", code: "es" },
  { id: 10, name: "Brazil", code: "br" },
  { id: 11, name: "Mexico", code: "mx" },
  { id: 12, name: "Argentina", code: "ar" },
  { id: 13, name: "South Africa", code: "za" },
  { id: 14, name: "Nigeria", code: "ng" },
  { id: 15, name: "Kenya", code: "ke" },
  { id: 16, name: "Egypt", code: "eg" },
  { id: 17, name: "China", code: "cn" },
  { id: 18, name: "Japan", code: "jp" },
  { id: 19, name: "South Korea", code: "kr" },
  { id: 20, name: "Singapore", code: "sg" },
  { id: 21, name: "Malaysia", code: "my" },
  { id: 22, name: "Thailand", code: "th" },
  { id: 23, name: "Vietnam", code: "vn" },
  { id: 24, name: "Indonesia", code: "id" },
  { id: 25, name: "Philippines", code: "ph" },
  { id: 26, name: "Russia", code: "ru" },
  { id: 27, name: "Ukraine", code: "ua" },
  { id: 28, name: "Poland", code: "pl" },
  { id: 29, name: "Netherlands", code: "nl" },
  { id: 30, name: "Sweden", code: "se" },
  { id: 31, name: "Norway", code: "no" },
  { id: 32, name: "Denmark", code: "dk" },
  { id: 33, name: "Finland", code: "fi" },
  { id: 34, name: "Switzerland", code: "ch" },
  { id: 35, name: "Austria", code: "at" },
  { id: 36, name: "Belgium", code: "be" },
  { id: 37, name: "Ireland", code: "ie" },
  { id: 38, name: "New Zealand", code: "nz" },
  { id: 39, name: "Saudi Arabia", code: "sa" },
  { id: 40, name: "United Arab Emirates", code: "ae" },
  { id: 41, name: "Turkey", code: "tr" },
  { id: 42, name: "Iran", code: "ir" },
  { id: 43, name: "Pakistan", code: "pk" },
  { id: 44, name: "Bangladesh", code: "bd" },
  { id: 45, name: "Sri Lanka", code: "lk" },
  { id: 46, name: "Nepal", code: "np" },
  { id: 47, name: "Bhutan", code: "bt" },
  { id: 48, name: "Maldives", code: "mv" },
  { id: 49, name: "Qatar", code: "qa" },
  { id: 50, name: "Kuwait", code: "kw" },
  { id: 51, name: "Oman", code: "om" },
  { id: 52, name: "Israel", code: "il" },
  { id: 53, name: "Greece", code: "gr" },
  { id: 54, name: "Portugal", code: "pt" },
  { id: 55, name: "Czech Republic", code: "cz" },
  { id: 56, name: "Hungary", code: "hu" },
  { id: 57, name: "Romania", code: "ro" },
  { id: 58, name: "Chile", code: "cl" },
  { id: 59, name: "Peru", code: "pe" },
  { id: 60, name: "Colombia", code: "co" },
];
