import type { Country } from "@/shared/interfaces";

export const COUNTRIES: Country[] = [
  { code: "IN", countryCode: "+91", label: "India", flag: "🇮🇳" },
  { code: "US", countryCode: "+1", label: "United States", flag: "🇺🇸" },
  { code: "GB", countryCode: "+44", label: "United Kingdom", flag: "🇬🇧" },
  { code: "CN", countryCode: "+86", label: "China", flag: "🇨🇳" },
  { code: "JP", countryCode: "+81", label: "Japan", flag: "🇯🇵" },
  { code: "DE", countryCode: "+49", label: "Germany", flag: "🇩🇪" },
  { code: "FR", countryCode: "+33", label: "France", flag: "🇫🇷" },
  { code: "RU", countryCode: "+7", label: "Russia", flag: "🇷🇺" },
  { code: "BR", countryCode: "+55", label: "Brazil", flag: "🇧🇷" },
  { code: "CA", countryCode: "+1", label: "Canada", flag: "🇨🇦" },
  { code: "AU", countryCode: "+61", label: "Australia", flag: "🇦🇺" },
  { code: "IT", countryCode: "+39", label: "Italy", flag: "🇮🇹" },
  { code: "ES", countryCode: "+34", label: "Spain", flag: "🇪🇸" },
  { code: "KR", countryCode: "+82", label: "South Korea", flag: "🇰🇷" },
  { code: "TR", countryCode: "+90", label: "Turkey", flag: "🇹🇷" },
  { code: "MX", countryCode: "+52", label: "Mexico", flag: "🇲🇽" },
  { code: "SG", countryCode: "+65", label: "Singapore", flag: "🇸🇬" },
  { code: "ID", countryCode: "+62", label: "Indonesia", flag: "🇮🇩" },
  { code: "SA", countryCode: "+966", label: "Saudi Arabia", flag: "🇸🇦" },
  { code: "NG", countryCode: "+234", label: "Nigeria", flag: "🇳🇬" },
  { code: "AR", countryCode: "+54", label: "Argentina", flag: "🇦🇷" },
  { code: "SE", countryCode: "+46", label: "Sweden", flag: "🇸🇪" },
  { code: "CH", countryCode: "+41", label: "Switzerland", flag: "🇨🇭" },
  { code: "NL", countryCode: "+31", label: "Netherlands", flag: "🇳🇱" },
  { code: "PL", countryCode: "+48", label: "Poland", flag: "🇵🇱" },
  { code: "BE", countryCode: "+32", label: "Belgium", flag: "🇧🇪" },
  { code: "AT", countryCode: "+43", label: "Austria", flag: "🇦🇹" },
  {
    code: "AE",
    countryCode: "+971",
    label: "United Arab Emirates",
    flag: "🇦🇪",
  },
  { code: "NZ", countryCode: "+64", label: "New Zealand", flag: "🇳🇿" },
  { code: "TH", countryCode: "+66", label: "Thailand", flag: "🇹🇭" },
  { code: "EG", countryCode: "+20", label: "Egypt", flag: "🇪🇬" },
  { code: "MY", countryCode: "+60", label: "Malaysia", flag: "🇲🇾" },
  { code: "QA", countryCode: "+974", label: "Qatar", flag: "🇶🇦" },
  { code: "NO", countryCode: "+47", label: "Norway", flag: "🇳🇴" },
  { code: "IE", countryCode: "+353", label: "Ireland", flag: "🇮🇪" },
  { code: "PH", countryCode: "+63", label: "Philippines", flag: "🇵🇭" },
  { code: "FI", countryCode: "+358", label: "Finland", flag: "🇫🇮" },
  { code: "GR", countryCode: "+30", label: "Greece", flag: "🇬🇷" },
  { code: "CZ", countryCode: "+420", label: "Czech Republic", flag: "🇨🇿" },
  { code: "DK", countryCode: "+45", label: "Denmark", flag: "🇩🇰" },
  { code: "PT", countryCode: "+351", label: "Portugal", flag: "🇵🇹" },
  { code: "IL", countryCode: "+972", label: "Israel", flag: "🇮🇱" },
  { code: "HU", countryCode: "+36", label: "Hungary", flag: "🇭🇺" },
  { code: "RO", countryCode: "+40", label: "Romania", flag: "🇷🇴" },
  { code: "UA", countryCode: "+380", label: "Ukraine", flag: "🇺🇦" },
  { code: "CO", countryCode: "+57", label: "Colombia", flag: "🇨🇴" },
  { code: "CL", countryCode: "+56", label: "Chile", flag: "🇨🇱" },
  { code: "BD", countryCode: "+880", label: "Bangladesh", flag: "🇧🇩" },
];
