import type { ICustomerGroup } from "@/pages/customer-groups/type/customerGroupMaster";

export const MOCK_CUSTOMER_GROUPS: ICustomerGroup[] = [
  {
    code: "RET",
    name: "Retail Customers",
    groupType: "Retail",
    discountPercent: 0,
    minOrderValue: 0,
    isDefault: true,
    isActive: true,
    description: "Default group for all retail customers.",
  },
  {
    code: "WHL",
    name: "Wholesale Partners",
    groupType: "Wholesale",
    discountPercent: 10,
    minOrderValue: 25000,
    isDefault: false,
    isActive: true,
    description: "Distributors and B2B buyers with wholesale pricing.",
  },
  {
    code: "VIP",
    name: "VIP Customers",
    groupType: "VIP",
    discountPercent: 15,
    minOrderValue: 50000,
    isDefault: false,
    isActive: true,
    description: "High-value repeat customers with premium support.",
  },
  {
    code: "EMP",
    name: "Employees",
    groupType: "Internal",
    discountPercent: 20,
    minOrderValue: 0,
    isDefault: false,
    isActive: true,
    description: "Internal employee purchase program.",
  },
  {
    code: "B2B-INTL",
    name: "International B2B",
    groupType: "B2B",
    discountPercent: 12,
    minOrderValue: 100000,
    isDefault: false,
    isActive: true,
    description: "Export and international corporate buyers.",
  },
  {
    code: "ARCH",
    name: "Archived Group",
    groupType: "Legacy",
    discountPercent: 5,
    minOrderValue: 0,
    isDefault: false,
    isActive: false,
    description: "Example inactive group for testing.",
  },
];
