import type { CustomerRow } from "@/pages/customer-master/type/customerMaster";

export const customerMasterMockData: CustomerRow[] = [
  {
    name: "Ashish Gupta",
    shortName: "AG",
    code: "001",
    maxUsers: "20",
    language: "English",
    description: "Navneet",
    locations: [
      {
        locationName: "Mumbai",
        locationShortName: "WH1",
        address: "123 Industrial Road",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        pincode: "400001",
        timezone: "IST",
        mobileNo: "9876543210",
        email: "warehouse@example.com",
        longitude: "72.8777",
        latitude: "19.0760",
        description: "Primary storage location",
      },
      {
        locationName: "Ahmedabad",
        locationShortName: "WH2",
        address: "123 Industrial Road",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        pincode: "400001",
        timezone: "IST",
        mobileNo: "9876543210",
        email: "warehouse@example.com",
        longitude: "72.8777",
        latitude: "19.0760",
        description: "Primary storage location",
      },
      {
        locationName: "Surat",
        locationShortName: "WH3",
        address: "123 Industrial Road",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        pincode: "400001",
        timezone: "IST",
        mobileNo: "9876543210",
        email: "warehouse@example.com",
        longitude: "72.8777",
        latitude: "19.0760",
        description: "Primary storage location",
      },
      {
        locationName: "Delhi",
        locationShortName: "WH4",
        address: "123 Industrial Road",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        pincode: "400001",
        timezone: "IST",
        mobileNo: "9876543210",
        email: "warehouse@example.com",
        longitude: "72.8777",
        latitude: "19.0760",
        description: "Primary storage location",
      },
    ],
  },
  {
    name: "Manav Prajapati",
    shortName: "MP",
    code: "002",
    maxUsers: "30",
    language: "English",
    description: "",
    locations: [
      {
        locationName: "Chennai",
        locationShortName: "CH",
        address: "45 Corporate Street",
        city: "Delhi",
        state: "Delhi",
        country: "India",
        pincode: "110001",
        timezone: "IST",
        mobileNo: "9123456789",
        email: "office@example.com",
        longitude: "77.1025",
        latitude: "28.7041",
        description: "Corporate headquarters",
      },
      {
        locationName: "Bangalore",
        locationShortName: "BA",
        address: "45 Corporate Street",
        city: "Delhi",
        state: "Delhi",
        country: "India",
        pincode: "110001",
        timezone: "IST",
        mobileNo: "9123456789",
        email: "office@example.com",
        longitude: "77.1025",
        latitude: "28.7041",
        description: "Corporate headquarters",
      },
      {
        locationName: "Hyderabad",
        locationShortName: "HY",
        address: "45 Corporate Street",
        city: "Delhi",
        state: "Delhi",
        country: "India",
        pincode: "110001",
        timezone: "IST",
        mobileNo: "9123456789",
        email: "office@example.com",
        longitude: "77.1025",
        latitude: "28.7041",
        description: "Corporate headquarters",
      },
    ],
  },
  {
    name: "Kishan Ambaliya",
    shortName: "KA",
    code: "003",
    maxUsers: "10",
    language: "English",
    locations: [
      {
        locationName: "Surat",
        locationShortName: "SU",
        address: "Tech Park Phase II",
        city: "Chennai",
        state: "Tamil Nadu",
        country: "India",
        pincode: "600032",
        timezone: "IST",
        mobileNo: "9998765432",
        email: "plant@example.com",
        longitude: "80.2707",
        latitude: "13.0827",
        description: "Manufacturing Plant",
      },
    ],
  },
  {
    name: "sahil Makwana",
    shortName: "SM",
    code: "004",
    maxUsers: "15",
    language: "English",
    locations: [
      {
        locationName: "Ahmedabad",
        locationShortName: "BO",
        address: "City Center Complex",
        city: "Ahmedabad",
        state: "Gujarat",
        country: "India",
        pincode: "380001",
        timezone: "IST",
        mobileNo: "9876001234",
        email: "branch@example.com",
        longitude: "72.5714",
        latitude: "23.0225",
        description: "Regional branch office",
      },
    ],
  },
  {
    name: "Vishvajit Vanar",
    shortName: "VV",
    code: "005",
    maxUsers: "20",
    language: "English",
    locations: [
      {
        locationName: "Pune",
        locationShortName: "PU",
        address: "IT Park Tower B",
        city: "Pune",
        state: "Maharashtra",
        country: "India",
        pincode: "411001",
        timezone: "IST",
        mobileNo: "9988776655",
        email: "support@example.com",
        longitude: "73.8567",
        latitude: "18.5204",
        description: "Technical support center",
      },
    ],
  },
  {
    name: "Himanshu",
    shortName: "HH",
    code: "006",
    maxUsers: "20",
    language: "English",
    locations: [
      {
        locationName: "Bangalore",
        locationShortName: "BA",
        address: "Workhub Plaza",
        city: "Bangalore",
        state: "Karnataka",
        country: "India",
        pincode: "560001",
        timezone: "IST",
        mobileNo: "9090909090",
        email: "remote@example.com",
        longitude: "77.5946",
        latitude: "12.9716",
        description: "Remote operations location",
      },
    ],
  },
  {
    name: "sahil",
    shortName: "SH",
    code: "007",
    maxUsers: "10",
    language: "English",
    locations: [
      {
        locationName: "Surat",
        locationShortName: "SU",
        address: "Sector 5 Industrial",
        city: "Surat",
        state: "Gujarat",
        country: "India",
        pincode: "395003",
        timezone: "IST",
        mobileNo: "9876541111",
        email: "temp@example.com",
        longitude: "72.8311",
        latitude: "21.1702",
        description: "Temporary project site",
      },
    ],
  },
  {
    name: "Ashish Gupta",
    shortName: "AG",
    code: "001",
    maxUsers: "20",
    language: "English",
    locations: [
      {
        locationName: "Mumbai",
        locationShortName: "MU",
        address: "123 Industrial Road",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        pincode: "400001",
        timezone: "IST",
        mobileNo: "9876543210",
        email: "warehouse@example.com",
        longitude: "72.8777",
        latitude: "19.0760",
        description: "Primary storage location",
      },
    ],
  },
  {
    name: "Manav Prajapati",
    shortName: "MP",
    code: "002",
    maxUsers: "30",
    language: "English",
    locations: [
      {
        locationName: "Delhi",
        locationShortName: "DE",
        address: "45 Corporate Street",
        city: "Delhi",
        state: "Delhi",
        country: "India",
        pincode: "110001",
        timezone: "IST",
        mobileNo: "9123456789",
        email: "office@example.com",
        longitude: "77.1025",
        latitude: "28.7041",
        description: "Corporate headquarters",
      },
    ],
  },
  {
    name: "Kishan Ambaliya",
    shortName: "KA",
    code: "003",
    maxUsers: "10",
    language: "English",
    locations: [
      {
        locationName: "Chennai",
        locationShortName: "CH",
        address: "Tech Park Phase II",
        city: "Chennai",
        state: "Tamil Nadu",
        country: "India",
        pincode: "600032",
        timezone: "IST",
        mobileNo: "9998765432",
        email: "plant@example.com",
        longitude: "80.2707",
        latitude: "13.0827",
        description: "Manufacturing Plant",
      },
    ],
  },
];
