import type { IDataPointTemplateRow } from "@/pages/data-point-master/types";

export const MOCK_DATA_POINT_TEMPLATES: IDataPointTemplateRow[] = [
  {
    srNo: 1,
    name: "Temperature Sensor A1",
    code: "TEMP_A1",
    dataType: "String",
    unit: "°C",
    pollingTime: "1s",
    tags: [
      {
        name: "Device Location",
        code: "001",
        datatype: "string[]",
        isMultiSelect: false,
        description: "Physical location of the asset",
        values: "Ahmedabad",
      },
      {
        name: "Company",
        code: "002",
        datatype: "string[]",
        isMultiSelect: true,
        description: "Company to which the asset belongs",
        values: "Navneet",
      },
    ],
  },
  {
    srNo: 2,
    name: "Pressure Gauge B2",
    code: "PRES_B2",
    dataType: "Boolean",
    unit: "PSI",
    pollingTime: "3s",
    tags: [
      {
        name: "Machine Category",
        code: "003",
        datatype: "string",
        isMultiSelect: false,
        description: "Category of the machine",
        values: "Production",
      },
      {
        name: "Company",
        code: "002",
        datatype: "string[]",
        isMultiSelect: true,
        description: "Company to which the asset belongs",
        values: "Navneet",
      },
    ],
  },
  {
    srNo: 3,
    name: "Motor Status C3",
    code: "MOTOR_C3",
    dataType: "Integer",
    unit: "On/Off",
    pollingTime: "onchange",
    tags: [
      {
        name: "Device Location",
        code: "001",
        datatype: "string[]",
        isMultiSelect: false,
        description: "Physical location of the asset",
        values: "Ahmedabad",
      },
      {
        name: "Company",
        code: "002",
        datatype: "string[]",
        isMultiSelect: true,
        description: "Company to which the asset belongs",
        values: "Navneet",
      },
    ],
  },
  {
    srNo: 4,
    name: "Flow Rate D4",
    code: "FLOW_D4",
    dataType: "Float",
    unit: "L/min",
    pollingTime: "5s",
    tags: [
      {
        name: "Machine Category",
        code: "003",
        datatype: "string",
        isMultiSelect: false,
        description: "Category of the machine",
        values: "Production",
      },
      {
        name: "Company",
        code: "002",
        datatype: "string[]",
        isMultiSelect: true,
        description: "Company to which the asset belongs",
        values: "Navneet",
      },
    ],
  },
  {
    srNo: 5,
    name: "Vibration Monitor E5",
    code: "VIB_E5",
    dataType: "Real",
    unit: "mm/s",
    pollingTime: "1s",
    tags: [
      {
        name: "Machine Category",
        code: "003",
        datatype: "string",
        isMultiSelect: false,
        description: "Category of the machine",
        values: "Production",
      },
      {
        name: "Company",
        code: "002",
        datatype: "string[]",
        isMultiSelect: true,
        description: "Company to which the asset belongs",
        values: "Navneet",
      },
    ],
  },
  {
    srNo: 6,
    name: "Humidity Sensor F6",
    code: "HUM_F6",
    dataType: "BooleanArray",
    unit: "% RH",
    pollingTime: "3s",
    tags: [
      {
        name: "Priority Level",
        code: "004",
        datatype: "number",
        isMultiSelect: false,
        description: "Priority level of the asset (1-10)",
        values: 5,
      },
      {
        name: "Machine Category",
        code: "003",
        datatype: "string",
        isMultiSelect: false,
        description: "Category of the machine",
        values: "Production",
      },
    ],
  },
  {
    srNo: 7,
    name: "Valve Controller G7",
    code: "VAL_G7",
    dataType: "Integer",
    unit: "Count",
    pollingTime: "onchange",
    tags: [
      {
        name: "Priority Level",
        code: "004",
        datatype: "number",
        isMultiSelect: false,
        description: "Priority level of the asset (1-10)",
        values: 5,
      },
      {
        name: "Machine Category",
        code: "003",
        datatype: "string",
        isMultiSelect: false,
        description: "Category of the machine",
        values: "Production",
      },
    ],
  },
  {
    srNo: 8,
    name: "Fuel Level H8",
    code: "FUEL_H8",
    dataType: "Float",
    unit: "Liters",
    pollingTime: "5s",
    tags: [
      {
        name: "Priority Level",
        code: "004",
        datatype: "number",
        isMultiSelect: false,
        description: "Priority level of the asset (1-10)",
        values: 5,
      },
      {
        name: "Machine Category",
        code: "003",
        datatype: "string",
        isMultiSelect: false,
        description: "Category of the machine",
        values: "Production",
      },
    ],
  },
  {
    srNo: 9,
    name: "Power Factor I9",
    code: "PWR_I9",
    dataType: "Float",
    unit: "PF",
    pollingTime: "1s",
    tags: [
      {
        name: "Priority Level",
        code: "004",
        datatype: "number",
        isMultiSelect: false,
        description: "Priority level of the asset (1-10)",
        values: 5,
      },
      {
        name: "Machine Category",
        code: "003",
        datatype: "string",
        isMultiSelect: false,
        description: "Category of the machine",
        values: "Production",
      },
      {
        name: "Company",
        code: "002",
        datatype: "string[]",
        isMultiSelect: true,
        description: "Company to which the asset belongs",
        values: "Navneet",
      },
    ],
  },
  {
    srNo: 10,
    name: "Oil Quality J10",
    code: "OIL_J10",
    dataType: "String",
    unit: "Index",
    pollingTime: "3s",
    tags: [
      {
        name: "Priority Level",
        code: "004",
        datatype: "number",
        isMultiSelect: false,
        description: "Priority level of the asset (1-10)",
        values: 5,
      },
      {
        name: "Machine Category",
        code: "003",
        datatype: "string",
        isMultiSelect: false,
        description: "Category of the machine",
        values: "Production",
      },
      {
        name: "Company",
        code: "002",
        datatype: "string[]",
        isMultiSelect: true,
        description: "Company to which the asset belongs",
        values: "Navneet",
      },
    ],
  },
];

export const findDatapointTemplate = (key?: string) =>
  MOCK_DATA_POINT_TEMPLATES.find(
    (template) => template.name === key || template.code === key
  );
