import type { DeviceTemplateRow } from "@/shared/types";

export const deviceMasterMockData: DeviceTemplateRow[] = [
  {
    srNo: 1,
    name: "BOLT RP",
    code: "TEMP_A1",
    description: "Temperature sensor for production line A",
    protocolType: "MODBUS_TCP/IP",
    attachedTags: [
      {
        name: "Device Location",
        code: "001",
        datatype: "string[]",
        isMultiSelect: false,
        description: "Physical location of the asset",
        values: "Ahmedabad",
      },
      {
        name: "Company",
        code: "002",
        datatype: "string[]",
        isMultiSelect: true,
        description: "Company to which the asset belongs",
        values: "Navneet",
      },
    ],
    attachedDatapoints: [],
  },
  {
    srNo: 2,
    name: "BOLT RP RF RF3",
    code: "PRES_B2",
    description: "Pressure monitoring device",
    protocolType: "OPC-UA",
    attachedTags: [
      {
        name: "Device Location",
        code: "001",
        datatype: "string[]",
        isMultiSelect: false,
        description: "Physical location of the asset",
        values: "Surat",
      },
      {
        name: "Machine Category",
        code: "003",
        datatype: "string",
        isMultiSelect: false,
        description: "Category of the machine",
        values: "Production",
      },
    ],
    attachedDatapoints: [],
  },
  {
    srNo: 3,
    name: "nOXA r6",
    code: "MOTOR_C3",
    description: "Motor control unit for assembly line",
    protocolType: "MODBUS_TCP/IP",
    attachedTags: [
      {
        name: "Device Location",
        code: "001",
        datatype: "string[]",
        isMultiSelect: false,
        description: "Physical location of the asset",
        values: "Rajkot",
      },
      {
        name: "Machine Category",
        code: "003",
        datatype: "string",
        isMultiSelect: false,
        description: "Category of the machine",
        values: "Production",
      },
    ],
    attachedDatapoints: [],
  },
  {
    srNo: 4,
    name: "BOLT RB MAX",
    code: "FLOW_C4",
    description: "Flow meter for liquid monitoring",
    protocolType: "MODBUS_RTU",
    attachedTags: [
      {
        name: "Device Location",
        code: "001",
        datatype: "string[]",
        isMultiSelect: false,
        description: "Physical location of the asset",
        values: "Ahmedabad",
      },
      {
        name: "Company",
        code: "002",
        datatype: "string[]",
        isMultiSelect: true,
        description: "Company to which the asset belongs",
        values: "Linomatic",
      },
    ],
    attachedDatapoints: [],
  },
  {
    srNo: 5,
    name: "SPRO B123",
    code: "VIB_E5",
    description: "Vibration sensor for machinery",
    protocolType: "MODBUS_TCP/IP",
    attachedTags: [
      {
        name: "Device Location",
        code: "001",
        datatype: "string[]",
        isMultiSelect: false,
        description: "Physical location of the asset",
        values: "Ahmedabad",
      },
      {
        name: "Is Active",
        code: "007",
        datatype: "boolean",
        isMultiSelect: false,
        description: "Whether the asset is currently active",
        values: true,
      },
    ],
    attachedDatapoints: [],
  },
  {
    srNo: 6,
    name: "CRM",
    code: "HUM_F6",
    description: "Humidity and temperature monitoring",
    protocolType: "OPC-UA",
    attachedTags: [
      {
        name: "Device Location",
        code: "001",
        datatype: "string[]",
        isMultiSelect: false,
        description: "Physical location of the asset",
        values: "Ahmedabad",
      },
      {
        name: "Company",
        code: "002",
        datatype: "string[]",
        isMultiSelect: true,
        description: "Company to which the asset belongs",
        values: "Linomatic",
      },
    ],
    attachedDatapoints: [],
  },
];
