import type { IDiscount } from "@/pages/discounts/type/discountMaster";

export const MOCK_DISCOUNTS: IDiscount[] = [
  {
    code: "WELCOME10",
    name: "Welcome 10% Off",
    type: "percentage",
    value: 10,
    minOrderValue: 0,
    maxDiscountValue: 500,
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    maxRedemptions: 1000,
    perCustomerLimit: 1,
    isActive: true,
    description: "10% off for new customers on their first order.",
  },
  {
    code: "FESTIVE500",
    name: "Festive Flat 500",
    type: "fixed",
    value: 500,
    minOrderValue: 5000,
    maxDiscountValue: 500,
    startDate: "2024-10-15",
    endDate: "2024-11-30",
    maxRedemptions: 500,
    perCustomerLimit: 2,
    isActive: true,
    description:
      "Flat 500 INR off on orders above 5000 INR during festive sale.",
  },
  {
    code: "BOGO-MOBILE",
    name: "Buy 1 Get 1 Mobile Case",
    type: "bogo",
    value: 0,
    minOrderValue: 0,
    startDate: "2024-08-01",
    endDate: "2024-08-31",
    maxRedemptions: 200,
    perCustomerLimit: 3,
    isActive: true,
    description:
      "Buy one mobile case and get another free (applied on eligible SKUs).",
  },
  {
    code: "FREESHIP999",
    name: "Free Shipping Over 999",
    type: "free_shipping",
    value: 0,
    minOrderValue: 999,
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    maxRedemptions: 0,
    perCustomerLimit: 0,
    isActive: true,
    description: "Free standard shipping for orders above 999 INR.",
  },
  {
    code: "ARCHIVE-DISC",
    name: "Archived Discount",
    type: "percentage",
    value: 5,
    minOrderValue: 0,
    maxDiscountValue: 200,
    startDate: "2023-01-01",
    endDate: "2023-12-31",
    maxRedemptions: 100,
    perCustomerLimit: 1,
    isActive: false,
    description: "Example inactive discount for testing.",
  },
];
