export const MOCK_INCIDENTS = [
    {
        id: 1,
        incidentId: "D0001",
        customer: "Ashish Gupta",
        machineNo: "11-12/50/0108",
        dateTime: "March 14, 2025, 09:42 AM",
        description: "Unexpected shutdown during operation.",
        photos: [
            "",
            "",
            "",
            "",
            "",
            "",
        ],
    },
    {
        id: 2,
        incidentId: "D0002",
        customer: "Manav Prajapati",
        machineNo: "11-22/60/0201",
        dateTime: "April 2, 2025, 10:35 AM",
        description: "High temperature alarm triggered repeatedly.",
        photos: [
            "",
            "",
            "",
        ],
    },
    {
        id: 3,
        incidentId: "D0003",
        customer: "Kishan Ambaliya",
        machineNo: "10-15/40/0305",
        dateTime: "June 10, 2025, 03:18 PM",
        description: "Network communication lost with PLC.",
        photos: [
            "",
            "",
        ],
    },
    {
        id: 4,
        incidentId: "D0004",
        customer: "Sahil Makwana",
        machineNo: "09-18/30/0402",
        dateTime: "August 5, 2025, 01:56 PM",
        description: "Frequent restart due to power fluctuation.",
        photos: [
            "",
            "",
        ],
    },
    {
        id: 5,
        incidentId: "D0005",
        customer: "Himanshu",
        machineNo: "12-20/55/0607",
        dateTime: "December 11, 2025, 02:27 PM",
        description: "Unexpected stop during batch production.",
        photos: [
            "",
            "",
        ],
    },
    {
        id: 6,
        incidentId: "D0006",
        customer: "Ashish Gupta",
        machineNo: "13-25/60/0709",
        dateTime: "January 5, 2026, 11:10 AM",
        description: "Vibration level exceeded threshold on spindle motor.",
        photos: [
            "",
            "",
        ],
    },
    {
        id: 7,
        incidentId: "D0007",
        customer: "Manav Prajapati",
        machineNo: "09-30/45/0210",
        dateTime: "February 19, 2026, 04:45 PM",
        description: "Emergency stop pressed by operator due to noise.",
        photos: [
            "",
            "",
        ],
    },
    {
        id: 8,
        incidentId: "D0008",
        customer: "Kishan Ambaliya",
        machineNo: "08-10/35/0311",
        dateTime: "March 28, 2026, 08:20 AM",
        description: "Axis overtravel alarm occurred during homing.",
        photos: [
            "",
        ],
    },
    {
        id: 9,
        incidentId: "D0009",
        customer: "Sahil Makwana",
        machineNo: "07-05/25/0412",
        dateTime: "April 9, 2026, 06:05 PM",
        description: "Coolant pump failure leading to overheating warning.",
        photos: [
            "",
            "",
        ],
    },
    {
        id: 10,
        incidentId: "D0010",
        customer: "Himanshu",
        machineNo: "15-40/70/0513",
        dateTime: "May 16, 2026, 09:55 AM",
        description: "Unexpected reboot after firmware update.",
        photos: [
            "",
            "",
        ],
    },
];
