export const MOCK_LANGUAGES = [
  {
    id: 1,
    name: "English",
    code: "en",
    description: "English",
    languageLabel: [
      {
        id: 1,
        labelName: "Acknowledge Alert",
        labelKey: "dashboard.alert.acknowledge",
        labelTag: "Acknowledge Alert",
      },
      {
        id: 2,
        labelName: "Acknowledge By",
        labelKey: "dashboard.alert.acknowledgeBy",
        labelTag: "Acknowledge By",
      },
      {
        id: 3,
        labelName: "Acknowledge Confirmation",
        labelKey: "dashboard.alert.confirmAcknowledge",
        labelTag: "Acknowledge Confirmation",
      },
      {
        id: 4,
        labelName: "Active Alerts",
        labelKey: "mainDashboard.alerts.activeAlerts",
        labelTag: "Active Alerts",
      },
      {
        id: 5,
        labelName: "Active Faults",
        labelKey: "mainDashboard.machineFaults.activeFaults",
        labelTag: "Active Faults",
      },
      {
        id: 6,
        labelName: "Active Machines",
        labelKey: "mainDashboard.machines.activeMachines",
        labelTag: "Active Machines",
      },
      {
        id: 7,
        labelName: "Active Status",
        labelKey: "users.form.activeStatus",
        labelTag: "Active Status",
      },
      {
        id: 8,
        labelName: "Active Value",
        labelKey: "mainDashboard.metrics.activeValue",
        labelTag: "Active Value",
      },
      {
        id: 9,
        labelName: "Add New Device",
        labelKey: "deviceManagement.addDevice",
        labelTag: "Add New Device",
      },
      {
        id: 10,
        labelName: "Add New User",
        labelKey: "users.list.addUser",
        labelTag: "Add New User",
      },
    ],
  },
  {
    id: 2,
    name: "Hindi",
    code: "hi",
    description: "Hindi",
    languageLabel: [
      {
        id: 1,
        labelName: "Acknowledge Alert",
        labelKey: "dashboard.alert.acknowledge",
        labelTag: "चेतावनी स्वीकार करें",
      },
      {
        id: 2,
        labelName: "Acknowledge By",
        labelKey: "dashboard.alert.acknowledgeBy",
        labelTag: "द्वारा स्वीकार किया गया",
      },
      {
        id: 3,
        labelName: "Acknowledge Confirmation",
        labelKey: "dashboard.alert.confirmAcknowledge",
        labelTag: "स्वीकृति की पुष्टि",
      },
      {
        id: 4,
        labelName: "Active Alerts",
        labelKey: "mainDashboard.alerts.activeAlerts",
        labelTag: "सक्रिय चेतावनियाँ",
      },
      {
        id: 5,
        labelName: "Active Faults",
        labelKey: "mainDashboard.machineFaults.activeFaults",
        labelTag: "सक्रिय त्रुटियाँ",
      },
      {
        id: 6,
        labelName: "Active Machines",
        labelKey: "mainDashboard.machines.activeMachines",
        labelTag: "सक्रिय मशीनें",
      },
      {
        id: 7,
        labelName: "Active Status",
        labelKey: "users.form.activeStatus",
        labelTag: "सक्रिय स्थिति",
      },
      {
        id: 8,
        labelName: "Active Value",
        labelKey: "mainDashboard.metrics.activeValue",
        labelTag: "सक्रिय मान",
      },
      {
        id: 9,
        labelName: "Add New Device",
        labelKey: "deviceManagement.addDevice",
        labelTag: "नया उपकरण जोड़ें",
      },
      {
        id: 10,
        labelName: "Add New User",
        labelKey: "users.list.addUser",
        labelTag: "नया उपयोगकर्ता जोड़ें",
      },
    ],
  },
  {
    id: 3,
    name: "Gujarati",
    code: "guj",
    description: "Gujarati",
    languageLabel: [
      {
        id: 1,
        labelName: "Acknowledge Alert",
        labelKey: "dashboard.alert.acknowledge",
        labelTag: "ચેતવણી સ્વીકારો",
      },
      {
        id: 2,
        labelName: "Acknowledge By",
        labelKey: "dashboard.alert.acknowledgeBy",
        labelTag: "દ્વારા સ્વીકારાયું",
      },
      {
        id: 3,
        labelName: "Acknowledge Confirmation",
        labelKey: "dashboard.alert.confirmAcknowledge",
        labelTag: "સ્વીકૃતિની પુષ્ટિ",
      },
      {
        id: 4,
        labelName: "Active Alerts",
        labelKey: "mainDashboard.alerts.activeAlerts",
        labelTag: "સક્રિય ચેતવણીઓ",
      },
      {
        id: 5,
        labelName: "Active Faults",
        labelKey: "mainDashboard.machineFaults.activeFaults",
        labelTag: "સક્રિય ખામીઓ",
      },
      {
        id: 6,
        labelName: "Active Machines",
        labelKey: "mainDashboard.machines.activeMachines",
        labelTag: "સક્રિય મશીનો",
      },
      {
        id: 7,
        labelName: "Active Status",
        labelKey: "users.form.activeStatus",
        labelTag: "સક્રિય સ્થિતિ",
      },
      {
        id: 8,
        labelName: "Active Value",
        labelKey: "mainDashboard.metrics.activeValue",
        labelTag: "સક્રિય મૂલ્ય",
      },
      {
        id: 9,
        labelName: "Add New Device",
        labelKey: "deviceManagement.addDevice",
        labelTag: "નવું ઉપકરણ ઉમેરો",
      },
      {
        id: 10,
        labelName: "Add New User",
        labelKey: "users.list.addUser",
        labelTag: "નવો યુઝર ઉમેરો",
      },
    ],
  },
  {
    id: 4,
    name: "Russian",
    code: "ru",
    description: "Russian",
    languageLabel: [
      {
        id: 1,
        labelName: "Acknowledge Alert",
        labelKey: "dashboard.alert.acknowledge",
        labelTag: "Подтвердить предупреждение",
      },
      {
        id: 2,
        labelName: "Acknowledge By",
        labelKey: "dashboard.alert.acknowledgeBy",
        labelTag: "Подтверждено",
      },
      {
        id: 3,
        labelName: "Acknowledge Confirmation",
        labelKey: "dashboard.alert.confirmAcknowledge",
        labelTag: "Подтверждение принятия",
      },
      {
        id: 4,
        labelName: "Active Alerts",
        labelKey: "mainDashboard.alerts.activeAlerts",
        labelTag: "Активные предупреждения",
      },
      {
        id: 5,
        labelName: "Active Faults",
        labelKey: "mainDashboard.machineFaults.activeFaults",
        labelTag: "Активные неисправности",
      },
      {
        id: 6,
        labelName: "Active Machines",
        labelKey: "mainDashboard.machines.activeMachines",
        labelTag: "Активные машины",
      },
      {
        id: 7,
        labelName: "Active Status",
        labelKey: "users.form.activeStatus",
        labelTag: "Активный статус",
      },
      {
        id: 8,
        labelName: "Active Value",
        labelKey: "mainDashboard.metrics.activeValue",
        labelTag: "Активное значение",
      },
      {
        id: 9,
        labelName: "Add New Device",
        labelKey: "deviceManagement.addDevice",
        labelTag: "Добавить новое устройство",
      },
      {
        id: 10,
        labelName: "Add New User",
        labelKey: "users.list.addUser",
        labelTag: "Добавить нового пользователя",
      },
    ],
  },
  {
    id: 5,
    name: "German",
    code: "ger",
    description: "German",
    languageLabel: [
      {
        id: 1,
        labelName: "Acknowledge Alert",
        labelKey: "dashboard.alert.acknowledge",
        labelTag: "Warnung bestätigen",
      },
      {
        id: 2,
        labelName: "Acknowledge By",
        labelKey: "dashboard.alert.acknowledgeBy",
        labelTag: "Bestätigt von",
      },
      {
        id: 3,
        labelName: "Acknowledge Confirmation",
        labelKey: "dashboard.alert.confirmAcknowledge",
        labelTag: "Bestätigung der Kenntnisnahme",
      },
      {
        id: 4,
        labelName: "Active Alerts",
        labelKey: "mainDashboard.alerts.activeAlerts",
        labelTag: "Aktive Warnungen",
      },
      {
        id: 5,
        labelName: "Active Faults",
        labelKey: "mainDashboard.machineFaults.activeFaults",
        labelTag: "Aktive Fehler",
      },
      {
        id: 6,
        labelName: "Active Machines",
        labelKey: "mainDashboard.machines.activeMachines",
        labelTag: "Aktive Maschinen",
      },
      {
        id: 7,
        labelName: "Active Status",
        labelKey: "users.form.activeStatus",
        labelTag: "Aktiver Status",
      },
      {
        id: 8,
        labelName: "Active Value",
        labelKey: "mainDashboard.metrics.activeValue",
        labelTag: "Aktiver Wert",
      },
      {
        id: 9,
        labelName: "Add New Device",
        labelKey: "deviceManagement.addDevice",
        labelTag: "Neues Gerät hinzufügen",
      },
      {
        id: 10,
        labelName: "Add New User",
        labelKey: "users.list.addUser",
        labelTag: "Neuen Benutzer hinzufügen",
      },
    ],
  },
];

export const DEFAULT_LANGUAGE_LABELS = [
  {
    id: 1,
    labelName: "Acknowledge Alert",
    labelKey: "dashboard.alert.acknowledge",
    labelTag: "Acknowledge Alert",
  },
  {
    id: 2,
    labelName: "Acknowledge By",
    labelKey: "dashboard.alert.acknowledgeBy",
    labelTag: "Acknowledge By",
  },
  {
    id: 3,
    labelName: "Acknowledge Confirmation",
    labelKey: "dashboard.alert.confirmAcknowledge",
    labelTag: "Acknowledge Confirmation",
  },
  {
    id: 4,
    labelName: "Active Alerts",
    labelKey: "mainDashboard.alerts.activeAlerts",
    labelTag: "Active Alerts",
  },
  {
    id: 5,
    labelName: "Active Faults",
    labelKey: "mainDashboard.machineFaults.activeFaults",
    labelTag: "Active Faults",
  },
  {
    id: 6,
    labelName: "Active Machines",
    labelKey: "mainDashboard.machines.activeMachines",
    labelTag: "Active Machines",
  },
  {
    id: 7,
    labelName: "Active Status",
    labelKey: "users.form.activeStatus",
    labelTag: "Active Status",
  },
  {
    id: 8,
    labelName: "Active Value",
    labelKey: "mainDashboard.metrics.activeValue",
    labelTag: "Active Value",
  },
  {
    id: 9,
    labelName: "Add New Device",
    labelKey: "deviceManagement.addDevice",
    labelTag: "Add New Device",
  },
  {
    id: 10,
    labelName: "Add New User",
    labelKey: "users.list.addUser",
    labelTag: "Add New User",
  },
];
