import type { IPaymentMethod } from "@/pages/payment-methods/type/paymentMethodMaster";

export const MOCK_PAYMENT_METHODS: IPaymentMethod[] = [
  {
    code: "UPI-RPAY",
    name: "UPI via Razorpay",
    methodType: "UPI",
    provider: "Razorpay",
    supportsOnline: true,
    supportsCod: false,
    transactionFeePercent: 0.5,
    settlementDays: 2,
    isActive: true,
    description: "UPI payments processed via Razorpay gateway.",
  },
  {
    code: "CARD-RPAY",
    name: "Cards via Razorpay",
    methodType: "Card",
    provider: "Razorpay",
    supportsOnline: true,
    supportsCod: false,
    transactionFeePercent: 2.0,
    fixedFee: 3,
    settlementDays: 2,
    isActive: true,
    description: "Credit/debit card payments.",
  },
  {
    code: "NB-PAYU",
    name: "NetBanking via PayU",
    methodType: "NetBanking",
    provider: "PayU",
    supportsOnline: true,
    supportsCod: false,
    transactionFeePercent: 1.5,
    settlementDays: 3,
    isActive: true,
    description: "Internet banking through multiple banks.",
  },
  {
    code: "COD-STD",
    name: "Cash on Delivery",
    methodType: "COD",
    provider: "In-house",
    supportsOnline: false,
    supportsCod: true,
    fixedFee: 30,
    settlementDays: 7,
    isActive: true,
    description: "Cash collection at delivery.",
  },
  {
    code: "WALLET-PAYTM",
    name: "Paytm Wallet",
    methodType: "Wallet",
    provider: "Paytm",
    supportsOnline: true,
    supportsCod: false,
    transactionFeePercent: 1.8,
    settlementDays: 2,
    isActive: true,
    description: "Wallet payments via Paytm.",
  },
  {
    code: "ARCH-PAY",
    name: "Legacy Payment Method",
    methodType: "Legacy",
    provider: "Old Gateway",
    supportsOnline: true,
    supportsCod: false,
    transactionFeePercent: 3,
    settlementDays: 5,
    isActive: false,
    description: "Example inactive payment method for testing.",
  },
];
