import type { IShippingMethod } from "@/pages/shipping-methods/type/shippingMethodMaster";

export const MOCK_SHIPPING_METHODS: IShippingMethod[] = [
  {
    code: "STD-DELH",
    name: "Delhivery Standard",
    carrier: "Delhivery",
    zone: "National",
    baseCharge: 50,
    perKgCharge: 20,
    estimatedDaysMin: 3,
    estimatedDaysMax: 7,
    isCodSupported: true,
    isActive: true,
    description: "Standard surface shipping across India.",
  },
  {
    code: "EXP-BLUD",
    name: "Blue Dart Express",
    carrier: "Blue Dart",
    zone: "Metro",
    baseCharge: 120,
    perKgCharge: 40,
    estimatedDaysMin: 1,
    estimatedDaysMax: 2,
    isCodSupported: false,
    isActive: true,
    description: "Express air courier for metro cities.",
  },
  {
    code: "LOC-AHD",
    name: "Ahmedabad Same Day",
    carrier: "Local Partner",
    zone: "Local",
    baseCharge: 30,
    perKgCharge: 15,
    estimatedDaysMin: 0,
    estimatedDaysMax: 1,
    isCodSupported: true,
    isActive: true,
    description: "Same-day local delivery within Ahmedabad.",
  },
  {
    code: "INT-DHL",
    name: "DHL International",
    carrier: "DHL",
    zone: "International",
    baseCharge: 800,
    perKgCharge: 200,
    estimatedDaysMin: 5,
    estimatedDaysMax: 10,
    isCodSupported: false,
    isActive: true,
    description: "International express shipping via DHL.",
  },
  {
    code: "ARCH-METHOD",
    name: "Archived Shipping Method",
    carrier: "Legacy Carrier",
    zone: "National",
    baseCharge: 100,
    perKgCharge: 30,
    estimatedDaysMin: 4,
    estimatedDaysMax: 8,
    isCodSupported: false,
    isActive: false,
    description: "Example inactive shipping method for testing.",
  },
];
