export const MOCK_STATES = [
  { id: 41, name: "São Paulo", code: "sp", country: "Brazil" },
  { id: 12, name: "New York", code: "ny", country: "United States" },
  { id: 3, name: "Karnataka", code: "kar", country: "India" },
  { id: 52, name: "Sichuan", code: "sc", country: "China" },
  { id: 24, name: "Tasmania", code: "tas", country: "Australia" },
  { id: 33, name: "Île-de-France", code: "idf", country: "France" },
  { id: 26, name: "Scotland", code: "sco", country: "United Kingdom" },
  { id: 15, name: "Ontario", code: "on", country: "Canada" },
  { id: 53, name: "Gauteng", code: "gau", country: "South Africa" },
  { id: 18, name: "Alberta", code: "ab", country: "Canada" },
  { id: 49, name: "Guangdong", code: "gd", country: "China" },
  { id: 11, name: "Florida", code: "fl", country: "United States" },
  { id: 22, name: "Queensland", code: "qld", country: "Australia" },
  {
    id: 34,
    name: "Provence-Alpes-Côte d'Azur",
    code: "paca",
    country: "France",
  },
  { id: 37, name: "Lombardy", code: "lom", country: "Italy" },
  { id: 7, name: "Kerala", code: "ker", country: "India" },
  { id: 58, name: "Tatarstan", code: "tat", country: "Russia" },
  { id: 10, name: "Texas", code: "tx", country: "United States" },
  { id: 30, name: "Berlin", code: "ber", country: "Germany" },
  { id: 40, name: "Tasmania", code: "tas", country: "Australia" },
  { id: 44, name: "Paraná", code: "pr", country: "Brazil" },
  { id: 1, name: "Gujarat", code: "guj", country: "India" },
  { id: 21, name: "Victoria", code: "vic", country: "Australia" },
  { id: 27, name: "Wales", code: "wal", country: "United Kingdom" },
  { id: 19, name: "Manitoba", code: "mb", country: "Canada" },
  { id: 5, name: "Rajasthan", code: "raj", country: "India" },
  { id: 39, name: "Western Australia", code: "waus", country: "Australia" },
  { id: 45, name: "Tokyo", code: "tok", country: "Japan" },
  { id: 55, name: "KwaZulu-Natal", code: "kzn", country: "South Africa" },
  { id: 59, name: "Jalisco", code: "jal", country: "Mexico" },
  { id: 2, name: "Maharashtra", code: "mah", country: "India" },
  { id: 17, name: "British Columbia", code: "bc", country: "Canada" },
  { id: 6, name: "Punjab", code: "pun", country: "India" },
  { id: 28, name: "Northern Ireland", code: "ni", country: "United Kingdom" },
  { id: 48, name: "Kyoto", code: "kyo", country: "Japan" },
  { id: 60, name: "Nuevo León", code: "nl", country: "Mexico" },
  { id: 13, name: "Illinois", code: "il", country: "United States" },
  { id: 14, name: "Washington", code: "wa", country: "United States" },
  { id: 50, name: "Beijing", code: "bj", country: "China" },
  { id: 23, name: "Western Australia", code: "waus", country: "Australia" },
  { id: 56, name: "Moscow", code: "mos", country: "Russia" },
  { id: 43, name: "Bahia", code: "bah", country: "Brazil" },
  { id: 29, name: "Bavaria", code: "bay", country: "Germany" },
  { id: 31, name: "Saxony", code: "sax", country: "Germany" },
  { id: 36, name: "Brittany", code: "bri", country: "France" },
  { id: 4, name: "Tamil Nadu", code: "tn", country: "India" },
  { id: 54, name: "Western Cape", code: "wc", country: "South Africa" },
  { id: 47, name: "Hokkaido", code: "hok", country: "Japan" },
  { id: 16, name: "Quebec", code: "qc", country: "Canada" },
  { id: 32, name: "Hesse", code: "hes", country: "Germany" },
  { id: 42, name: "Rio de Janeiro", code: "rj", country: "Brazil" },
  { id: 20, name: "New South Wales", code: "nsw", country: "Australia" },
  { id: 46, name: "Osaka", code: "osk", country: "Japan" },
  { id: 8, name: "West Bengal", code: "wb", country: "India" },
  { id: 57, name: "Saint Petersburg", code: "spb", country: "Russia" },
  { id: 35, name: "Normandy", code: "nor", country: "France" },
  { id: 38, name: "Tuscany", code: "tus", country: "Italy" },
  { id: 9, name: "California", code: "ca", country: "United States" },
];
