import type { ISupplier } from "@/pages/suppliers/type/supplierMaster";

export const MOCK_SUPPLIERS: ISupplier[] = [
  {
    code: "SUP-DELH",
    name: "Delhivery Logistics",
    contactName: "Rohit Verma",
    phone: "+91-9876543210",
    email: "sales@delhivery.com",
    country: "India",
    city: "Gurugram",
    leadTimeDays: 3,
    minOrderValue: 0,
    paymentTerms: "30 days credit",
    isActive: true,
    description:
      "National logistics partner for standard and express deliveries.",
  },
  {
    code: "SUP-BLUED",
    name: "Blue Dart",
    contactName: "Anita Singh",
    phone: "+91-9988776655",
    email: "keyaccounts@bluedart.com",
    country: "India",
    city: "Mumbai",
    leadTimeDays: 2,
    minOrderValue: 0,
    paymentTerms: "Prepaid & weekly billing",
    isActive: true,
    description: "Air and surface courier partner for metro deliveries.",
  },
  {
    code: "SUP-ELC-IMP",
    name: "ElectroImports LLC",
    contactName: "John Miller",
    phone: "+1-415-555-0123",
    email: "orders@electroimports.com",
    country: "United States",
    city: "San Francisco",
    leadTimeDays: 10,
    minOrderValue: 50000,
    paymentTerms: "Advance 30% / 70% on dispatch",
    isActive: true,
    description: "Importer of high-end electronics and accessories.",
  },
  {
    code: "SUP-LOCAL-WH",
    name: "Ahmedabad Local Wholesale",
    contactName: "Mahesh Patel",
    phone: "+91-9090909090",
    email: "mahesh@localwholesale.in",
    country: "India",
    city: "Ahmedabad",
    leadTimeDays: 1,
    minOrderValue: 10000,
    paymentTerms: "Cash on delivery",
    isActive: true,
    description: "Local distributor for fashion and lifestyle products.",
  },
  {
    code: "SUP-RETURNS",
    name: "Returns Consolidation Partner",
    contactName: "Support Team",
    phone: "+91-8000000000",
    email: "returns@rcp.com",
    country: "India",
    city: "Mumbai",
    leadTimeDays: 5,
    minOrderValue: 0,
    paymentTerms: "Monthly settlement",
    isActive: true,
    description: "Handles reverse logistics and returns consolidation.",
  },
  {
    code: "SUP-INACTIVE",
    name: "Legacy Supplier",
    contactName: "N/A",
    phone: "",
    email: "",
    country: "India",
    city: "",
    leadTimeDays: 7,
    minOrderValue: 0,
    paymentTerms: "",
    isActive: false,
    description: "Example inactive supplier for testing.",
  },
];
