import type { ITaxRate } from "@/pages/tax-rates/type/taxRateMaster";

export const MOCK_TAX_RATES: ITaxRate[] = [
  {
    code: "IN-GST-STD",
    name: "India GST Standard",
    country: "India",
    state: "All",
    taxType: "GST",
    ratePercent: 18,
    isInclusive: false,
    isActive: true,
    description: "Default GST rate for most goods and services in India.",
  },
  {
    code: "IN-GST-RED",
    name: "India GST Reduced",
    country: "India",
    state: "All",
    taxType: "GST",
    ratePercent: 12,
    isInclusive: false,
    isActive: true,
    description: "Reduced GST slab for selected categories.",
  },
  {
    code: "IN-GJ-GST",
    name: "India GST Gujarat",
    country: "India",
    state: "Gujarat",
    taxType: "GST",
    ratePercent: 18,
    isInclusive: false,
    isActive: true,
    description: "Example regional tax rule for Gujarat.",
  },
  {
    code: "IN-ZERO",
    name: "India Zero Rated",
    country: "India",
    taxType: "GST",
    ratePercent: 0,
    isInclusive: false,
    isActive: true,
    description: "Zero rated goods/services.",
  },
  {
    code: "EU-VAT-STD",
    name: "EU VAT Standard",
    country: "EU",
    taxType: "VAT",
    ratePercent: 20,
    isInclusive: true,
    isActive: true,
    description: "Standard VAT rate example for EU countries.",
  },
  {
    code: "ARCH-TAX",
    name: "Archived Tax Rule",
    country: "India",
    taxType: "Legacy",
    ratePercent: 5,
    isInclusive: false,
    isActive: false,
    description: "Example inactive tax rate for testing.",
  },
];
