export const MOCK_USERS = [
  {
    id: 1,
    srNo: 1,
    name: "Ankur Gupta",
    role: "Admin",
    customer: "Ashish Gupta",
    mobile: "9876543210",
    email: "ankur.g@example.com",
    active: true,
    machineCodes: [],
  },
  {
    id: 2,
    srNo: 2,
    name: "Kabir Prajapati",
    role: "Admin",
    customer: "Manav Prajapati",
    mobile: "9988776555",
    email: "kabir.p@example.com",
    active: true,
    machineCodes: [],
  },
  {
    id: 3,
    srNo: 3,
    name: "Krunal Ambaliya",
    role: "Admin",
    customer: "Kishan Ambaliya",
    mobile: "9234567890",
    email: "krunal.a@example.com",
    active: false,
    machineCodes: [],
  },
  {
    id: 4,
    srNo: 4,
    name: "Rahul Makwana",
    role: "User",
    customer: "Sahil Makwana",
    mobile: "8000112233",
    email: "rahul.m@example.com",
    active: true,
    machineCodes: ["24-25/S0/12348","24-25/S0/12349","24-25/S0/12347"],
  },
  {
    id: 5,
    srNo: 5,
    name: "Raj Vanar",
    role: "User",
    customer: "Vishvajit Vanar",
    mobile: "7654321098",
    email: "raj.v@example.com",
    active: true,
    machineCodes: ["24-25/S0/12349","24-25/S0/12345"],
  },
  {
    id: 6,
    srNo: 6,
    name: "Dev",
    role: "User",
    customer: "Himanshu",
    mobile: "9000011111",
    email: "dev.s@example.com",
    active: false,
    machineCodes: ["24-25/S0/12345"],
  },
  {
    id: 7,
    srNo: 7,
    name: "Janak",
    role: "Admin",
    customer: "Sahil",
    mobile: "8878878787",
    email: "janak.m@example.com",
    active: true,
    machineCodes: [],
  },
];
